//
//  FavouriteModels.swift
//  MirianMaglakelidze#26
//
//  Created by Admin on 8/26/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favourite
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request {}
    struct Response {
        var notes: [MyNote]
    }
    struct ViewModel {
        var notes: [MyNote]
    }
  }
}
