//
//  FavouriteWorker.swift
//  MirianMaglakelidze#26
//
//  Created by Admin on 8/26/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class FavouriteWorker {
    func getNoteUsingPredicate(complition: @escaping (Result<[MyNote], Error>) ->Void) {
        let managedContext = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
        let fetchRequset: NSFetchRequest<MyNote> = MyNote.fetchRequest()
        fetchRequset.predicate = NSPredicate(format: "isFavourite == %@", "1")
        do {
            let notes = try managedContext.fetch(fetchRequset)
            complition(.success(notes))
        } catch  {
            complition(.failure(error))
        }
    }
}
