//
//  NotePresenter.swift
//  MirianMaglakelidze#26
//
//  Created by Admin on 8/26/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotePresentationLogic {
  func presentFetchResult(response: Note.CoreData.Response)
    func presentDeleteResult(respons: Note.RemoveNote.Response)
}

class NotePresenter: NotePresentationLogic {
    
  weak var viewController: NoteDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchResult(response: Note.CoreData.Response) {
    var viewModel = Note.CoreData.ViewModel()
    switch response.result {
    case.success(let notes):
        guard let myNotes = (notes as? [MyNote]) else { return }
        viewModel.myNote = myNotes
    case.failure(let error):
        viewModel.error = error.localizedDescription
    }
    viewController?.displayNote(viewModel: viewModel)
  }
    
    func presentDeleteResult(respons: Note.RemoveNote.Response) {
        let viewModel = Note.RemoveNote.ViewModel(error: respons.error?.localizedDescription)
        viewController?.displayDeleteError(viewModel: viewModel)
        
    }

}
