//
//  AddInteractor.swift
//  MirianMaglakelidze#26
//
//  Created by Admin on 8/26/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddBusinessLogic {
  func addNewNote(request: Add.Note.Request)
}

protocol AddDataStore {
  //var name: String { get set }
}

class AddInteractor: AddBusinessLogic, AddDataStore {
  var presenter: AddPresentationLogic?
  var worker: AddWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func addNewNote(request: Add.Note.Request) {
    worker = AddWorker()
    worker?.saveNewNoteToCoreData(note: request.note, complition: { [weak self] error in
        let response = Add.Note.Response(error: error)
        self?.presenter?.presentError(response: response)
    })
  }
}
