//
//  AddWorker.swift
//  MirianMaglakelidze#26
//
//  Created by Admin on 8/26/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class AddWorker {
    func saveNewNoteToCoreData(note: NoteForme, complition: @escaping (Error?) -> Void) {
        guard let context = (UIApplication.shared.delegate as? AppDelegate)?.persistentContainer.viewContext else { return }
        let newNote = MyNote(context: context)
        newNote.info = note.info
        newNote.title = note.title
        newNote.isFavourite = note.isFavourite
        newNote.creationDate = note.createDate
        do {
            try context.save()
            complition(nil)
        } catch {
            complition(error)
        }
    }
}
